config/routes.rb
Rails.application.routes.draw do
  resources :hermits
  # get 'pages/index'
  get 'pages/about', as: :about
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hermit.rb
class Hermit < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hermits_controller.rb
class HermitsController < ApplicationController
  before_action :set_hermit, only: %i[ show edit update destroy ]

  # GET /hermits or /hermits.json
  def index
    @hermits = Hermit.all
  end

  # GET /hermits/1 or /hermits/1.json
  def show
  end

  # GET /hermits/new
  def new
    @hermit = Hermit.new
  end

  # GET /hermits/1/edit
  def edit
  end

  # POST /hermits or /hermits.json
  def create
    @hermit = Hermit.new(hermit_params)

    respond_to do |format|
      if @hermit.save
        format.html { redirect_to hermit_url(@hermit), notice: "Hermit was successfully created." }
        format.json { render :show, status: :created, location: @hermit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hermit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hermits/1 or /hermits/1.json
  def update
    respond_to do |format|
      if @hermit.update(hermit_params)
        format.html { redirect_to hermit_url(@hermit), notice: "Hermit was successfully updated." }
        format.json { render :show, status: :ok, location: @hermit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hermit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hermits/1 or /hermits/1.json
  def destroy
    @hermit.destroy!

    respond_to do |format|
      format.html { redirect_to hermits_url, notice: "Hermit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hermit
      @hermit = Hermit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hermit_params
      params.require(:hermit).permit(:start_year, :alias, :subs, :description, :youtube, :twitch, :twitter, :instagram, :patreon, :skin_alt, :face_alt)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hermits_helper.rb
module HermitsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/hermits/_form.html.erb
<%= form_with(model: hermit, class: "contents") do |form| %>
  <% if hermit.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(hermit.errors.count, "error") %> prohibited this hermit from being saved:</h2>

      <ul>
        <% hermit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :start_year %>
    <%= form.number_field :start_year, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :alias %>
    <%= form.text_field :alias, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :subs %>
    <%= form.text_field :subs, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :youtube %>
    <%= form.text_area :youtube, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :twitch %>
    <%= form.text_area :twitch, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :twitter %>
    <%= form.text_area :twitter, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :instagram %>
    <%= form.text_area :instagram, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :patreon %>
    <%= form.text_area :patreon, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :skin_alt %>
    <%= form.text_field :skin_alt, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :face_alt %>
    <%= form.text_field :face_alt, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/hermits/_hermit.html.erb
<div id="<%= dom_id hermit %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Start year:</strong>
    <%= hermit.start_year %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Alias:</strong>
    <%= hermit.alias %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Subs:</strong>
    <%= hermit.subs %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= hermit.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Youtube:</strong>
    <%= hermit.youtube %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Twitch:</strong>
    <%= hermit.twitch %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Twitter:</strong>
    <%= hermit.twitter %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Instagram:</strong>
    <%= hermit.instagram %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Patreon:</strong>
    <%= hermit.patreon %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Skin alt:</strong>
    <%= hermit.skin_alt %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Face alt:</strong>
    <%= hermit.face_alt %>
  </p>

</div>

app/views/hermits/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing hermit</h1>

  <%= render "form", hermit: @hermit %>

  <%= link_to "Show this hermit", @hermit, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to hermits", hermits_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/hermits/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Hermits" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Hermits</h1>
    <%= link_to "New hermit", new_hermit_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="hermits" class="min-w-full">
    <% @hermits.each do |hermit| %>
      <%= render hermit %>
      <p>
        <%= link_to "Show this hermit", hermit, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/hermits/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New hermit</h1>

  <%= render "form", hermit: @hermit %>

  <%= link_to "Back to hermits", hermits_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/hermits/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @hermit %>

    <%= link_to "Edit this hermit", edit_hermit_path(@hermit), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to hermits", hermits_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this hermit", @hermit, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="bg-hermit-green text-black top-0">
  <div class="container flex mx-auto px-5 py-3 flex-wrap justify-between">
    <h1 class="text-lg font-semibold"><%= link_to "Hermit Plus", root_path %></h1>
    <ul class="flex gap-[40px] text-m">
      <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
      <li>contact</li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hermits</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<div>
  <h1 class="font-bold text-4xl">Pages#about</h1>
  <p>Find me in app/views/pages/about.html.erb</p>
</div>

app/views/pages/index.html.erb
<div>
  <h1 class="font-teko font-bold text-4xl">Pages#index</h1>
  <p class="font-kanit">Find me in app/views/pages/index.html.erb</p>
</div>